/*
Copyright CMSS Chinamobile Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tidb-incubator/Serverlessdb-for-HTAP/pkg/sldb-operator/apis/bcrds/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServerlessDBs implements ServerlessDBInterface
type FakeServerlessDBs struct {
	Fake *FakeBcrdsV1alpha1
	ns   string
}

var serverlessdbsResource = schema.GroupVersionResource{Group: "bcrds.cmss.com", Version: "v1alpha1", Resource: "serverlessdbs"}

var serverlessdbsKind = schema.GroupVersionKind{Group: "bcrds.cmss.com", Version: "v1alpha1", Kind: "ServerlessDB"}

// Get takes name of the serverlessDB, and returns the corresponding serverlessDB object, and an error if there is any.
func (c *FakeServerlessDBs) Get(name string, options v1.GetOptions) (result *v1alpha1.ServerlessDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serverlessdbsResource, c.ns, name), &v1alpha1.ServerlessDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessDB), err
}

// List takes label and field selectors, and returns the list of ServerlessDBs that match those selectors.
func (c *FakeServerlessDBs) List(opts v1.ListOptions) (result *v1alpha1.ServerlessDBList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serverlessdbsResource, serverlessdbsKind, c.ns, opts), &v1alpha1.ServerlessDBList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServerlessDBList{ListMeta: obj.(*v1alpha1.ServerlessDBList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServerlessDBList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serverlessDBs.
func (c *FakeServerlessDBs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serverlessdbsResource, c.ns, opts))

}

// Create takes the representation of a serverlessDB and creates it.  Returns the server's representation of the serverlessDB, and an error, if there is any.
func (c *FakeServerlessDBs) Create(serverlessDB *v1alpha1.ServerlessDB) (result *v1alpha1.ServerlessDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serverlessdbsResource, c.ns, serverlessDB), &v1alpha1.ServerlessDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessDB), err
}

// Update takes the representation of a serverlessDB and updates it. Returns the server's representation of the serverlessDB, and an error, if there is any.
func (c *FakeServerlessDBs) Update(serverlessDB *v1alpha1.ServerlessDB) (result *v1alpha1.ServerlessDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serverlessdbsResource, c.ns, serverlessDB), &v1alpha1.ServerlessDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessDB), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServerlessDBs) UpdateStatus(serverlessDB *v1alpha1.ServerlessDB) (*v1alpha1.ServerlessDB, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(serverlessdbsResource, "status", c.ns, serverlessDB), &v1alpha1.ServerlessDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessDB), err
}

// Delete takes name of the serverlessDB and deletes it. Returns an error if one occurs.
func (c *FakeServerlessDBs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(serverlessdbsResource, c.ns, name), &v1alpha1.ServerlessDB{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServerlessDBs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serverlessdbsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServerlessDBList{})
	return err
}

// Patch applies the patch and returns the patched serverlessDB.
func (c *FakeServerlessDBs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServerlessDB, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serverlessdbsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServerlessDB{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServerlessDB), err
}
